apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "spoke.labels" . | nindent 4 }}
  annotations:
    haproxy.org/server-ssl: "true"
spec:
  clusterIP: None
  ports:
  - name: https-spoke
    port: 8080
    targetPort: 8080
  selector:
    {{- include "spoke.selectorLabels" . | nindent 4 }}
