apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "photomnemonic.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: photomnemonic
  selector:
    {{- include "photomnemonic.selectorLabels" . | nindent 4 }}
