{{- if .Values.configTCP.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Chart.Name }}-tcp-config
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
data:
  "5349": {{ .Release.Namespace }}/coturn:5349
{{- end}}