{{- if .Values.LoadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-lb
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.LoadBalancer.type }}
  {{ .Values.LoadBalancer.spec | toYaml | nindent 2 }}
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}

{{- end }}