{{- if .Values.clusterRoleBinding.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-cr
subjects:
  - kind: ServiceAccount
    name: haproxy-sa
    namespace: {{ .Release.Namespace }}
{{- end }}