apiVersion: v1
kind: Service
metadata:
  name: coturn
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  # {{- if .Values.service.type }}type: {{ .Values.service.type }}{{- end }}
  ports:
  - name: https-coturn
    port: 5349
    targetPort: 5349
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
