apiVersion: v1
kind: Service
metadata:
  name: nearspark
  labels:
    {{- include "nearspark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    {{- include "nearspark.selectorLabels" . | nindent 4 }}
