{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dialog.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dialog.labels" . | nindent 4 }}
  annotations: 
    kubernetes.io/ingress.class: haproxy
    haproxy.org/server-ssl: "true"
    haproxy.org/load-balance: "url_param roomId"
spec:
  tls:
    - hosts:
        - stream.{{ .Values.global.domain }}
      secretName: cert-stream.{{ .Values.global.domain }}
  rules:
    - host: stream.{{ .Values.global.domain }}
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialog
                port: 
                  number: 4443

  {{- end }}
