apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "dialog.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: https-dialog
    port: 4443
    targetPort: 4443
  - name: https-dialog-adm
    port: 7000
    targetPort: 7000
  selector:
    {{- include "dialog.selectorLabels" . | nindent 4 }}
