{{- if .Values.global.aws.efs.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pgsql.fullname" . }}-efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Release.Name }}-efs-storage-class
  resources:
    requests:
      storage: 5Gi

{{- end}}