{{- if .Values.configs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: configs
  labels:
    {{- include "hubs-ce.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.configs.data | nindent 2 }}

{{- end}}