{{- if .Values.defaultCert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultCert.name }}
  labels:
    {{- include "hubs-ce.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.defaultCert.data | nindent 4 }}
{{- end}} 