apiVersion: v1
kind: Service
metadata:
  name: hubs
  labels:
    {{- include "hubs-ce.labels" . | nindent 4 }}
  annotations:
    haproxy.org/server-ssl: "true"
spec:
  clusterIP: None
  ports:
  - name: https-hubs
    port: 8080
    targetPort: 8080
  selector:
    {{- include "hubs-ce.selectorLabels" . | nindent 4 }}
